<style type="text/css">
body.dragging, body.dragging * {
  cursor: move !important;
}

.dragged {
  position: absolute;
  opacity: 0.5;
  z-index: 2000;
}

ol.example li.placeholder {
  position: relative;
  /** More li styles **/
}
ol.example li.placeholder:before {
  position: absolute;
  /** Define arrowhead **/
}
</style>
<div class="page-header">
    <?php $room = require_once APP_PATH.('config/room.php'); ?>
    <h3>Danh sách chờ <?=$room[$r]?></h3>
</div>
<div class="col-md-3" style="padding-left:0">
<strong style="font-size: 24px;">Bệnh nhân thường</strong>
<table class="table table-striped table-bordered sorted_table">
    <thead>
      <tr style="font-size: 20px;height: 75px;">
        <th><input type="checkbox" id="check_all"></th>
        <th style="font-size: 20px;">STT</th>
        <th style="font-size: 20px;">Tên Bệnh nhân</th>
        <th style="font-size: 20px;">Ngày sinh</th>
        <th style="font-size: 20px;">Giới tính</th>
        <th style="font-size: 20px;">Hành động</th>
      </tr>
    </thead>
    <tbody id="drapTable">
      <?php 
      $count = 0;
      $bnKey = array();
      foreach($bNhan as $b):
        $check = array_search($b->id,$bnKey);
        if($check === false){
          $count++;
          $bnKey[] = $b->id;
        }
      ?>
      <tr style="height: 75px;<?php if($b->status == 1 && $count==1): ?>background-color: forestgreen;<?php endif; ?>">
        <td class="row"><input type="checkbox" value="<?= $b->id ?>" class="selected_bnhan" name="bnhan_id[]"></td>
        <td style="font-size: 20px;"><?=$count?></td>
        <td style="font-size: 20px;"><?=$b->TEN_BNHAN?></td>
        <td style="font-size: 20px;"><?=$b->NGAY_SINH?></td>
        <td style="font-size: 20px;"><?php if($b->GIOI_TINH == 'M'){echo "Nam";}else{echo "Nữ";}?></td>
        <td style="font-size: 20px;">
          <?php if($count == 1){ ?>
            <?php if($b->status == 0): ?>
             <strong>Gọi vào</strong>
            <?php endif; ?>
            <?php if($b->status == 1): ?>
             <strong>Đang khám</strong>
            <?php endif; ?>
          <?php }else{
              echo "<strong>Đang đợi</strong>";  
          } ?>
        </td>
      </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
</div>

<div class="col-md-3" style="margin-left: 15%;">
<strong style="font-size: 24px;">Bệnh nhân đặt hẹn</strong>
<table class="table table-striped table-bordered sorted_table_vip">
    <thead>
      <tr style="font-size: 20px;height: 75px;">
        <th><input type="checkbox" id="check_all"></th>
        <th style="font-size: 20px;">STT</th>
        <th style="font-size: 20px;">Tên Bệnh nhân</th>
        <th style="font-size: 20px;">Ngày sinh</th>
        <th style="font-size: 20px;">Giới tính</th>
        <th style="font-size: 20px;">Hành động</th>
      </tr>
    </thead>
    <tbody id="drapTable">
      <?php 
      $count = 0;
      $bnKey = array();
      foreach($vip as $b):
        $check = array_search($b->id,$bnKey);
        if($check === false){
          $count++;
          $bnKey[] = $b->id;
        }
      ?>
      <tr style="height: 75px;<?php if($b->status == 1 && $count==1): ?>background-color: forestgreen;<?php endif; ?>">
        <td class="row"><input type="checkbox" value="<?= $b->id ?>" class="selected_bnhan" name="bnhan_id[]"></td>
        <td style="font-size: 20px;"><?=$count?></td>
        <td style="font-size: 20px;"><?=$b->TEN_BNHAN?></td>
        <td style="font-size: 20px;"><?=$b->NGAY_SINH?></td>
        <td style="font-size: 20px;"><?php if($b->GIOI_TINH == 'M'){echo "Nam";}else{echo "Nữ";}?></td>
        <td style="font-size: 20px;">
          <?php if($count == 1){ ?>
            <?php if($b->status == 0): ?>
             <strong>Gọi vào</strong>
            <?php endif; ?>
            <?php if($b->status == 1): ?>
             <strong>Đang khám</strong>
            <?php endif; ?>
          <?php }else{
              echo "<strong>Đang đợi</strong>";  
          } ?>
        </td>
      </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
</div>


<div class="col-md-1" style="margin-left: 243px;width: 13.5%;margin-top: 33px;padding-right:0;">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>Khách thường</strong>
                </div>
                <div class="panel-body">
                <strong></strong>
                        <div class="btn-group" style="margin-top: 15px;">
                          <?php if($bNhan[0]->status == 0): ?>
                            <button type="button" class="btn btn-danger" onclick="callRefresh('1','<?=$bNhan[0]->BENH_NHAN_ID?>');">Gọi vào</button>
                          <?php endif; ?>
                          <?php if($bNhan[0]->status == 1): ?>
                           <button type="button" class="btn btn-primary" onclick="callRefresh('2','<?=$bNhan[0]->BENH_NHAN_ID?>');">Khám xong</button>
                          <?php endif; ?>
                        </div>
                    </div>
                </div>
                
                
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong style="color: red;">Khách đặt hẹn</strong>
                </div>
                <div class="panel-body">
                <strong></strong>
                        <div class="btn-group" style="margin-top: 15px;">
                          <?php if($vip[0]->status == 0): ?>
                            <button type="button" class="btn btn-danger" onclick="callRefresh('1','<?=$vip[0]->BENH_NHAN_ID?>');">Gọi vào</button>
                          <?php endif; ?>
                          <?php if($vip[0]->status == 1): ?>
                           <button type="button" class="btn btn-primary" onclick="callRefresh('2','<?=$vip[0]->BENH_NHAN_ID?>');">Khám xong</button>
                          <?php endif; ?>
                        </div>
                    </div>
                </div>
                
                
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>Chuyển phòng</strong>
                </div>
                <div class="panel-body">
                        <div class="btn-group">
                                <select name="room" class="form-control" id="swapRoom">
                                    <?php foreach($room as $key=>$value): ?>
                                      <option value="<?=$key?>"><?=$value?></option>
                                    <?php endforeach; ?>
                                </select>
                        </div>
                        <div class="btn-group" style="margin-top: 15px;">
                          <button type="button" id="swapBnhan" class="ajax-link btn btn-success tooltip-item"><span class="glyphicon glyphicon-plus"></span>&nbsp;&nbsp;Chuyển</button>
                        </div>
                    </div>
                </div>
            </div>
            </div>
  
        </div>
<script>
  var socket = io.connect('<?=NODE_SERVER?>');
  
  function callRefresh(sta,bid){
    $.get( "/room", { status: sta, id: bid } )
    .done(function( data ) {
      socket.emit('chatMessage', "callBNhan");
      location.reload();
    });
    
    //$(location).attr('href',"/room?status="+sta+"&id="+bid);
    //window.location("/room?status="+sta+"&id="+bid);
  }

  socket.on('chatMessage', function(msg){
    if(msg == "swap" || msg == "pushBNhan"){
      location.reload();
    }
  });

  // Sortable rows
  var oldIndex;
  $('.sorted_table').sortable({
    containerSelector: 'table',
    itemPath: '> tbody',
    itemSelector: 'tr',
    placeholder: '<tr class="placeholder"/>',
    onDragStart: function ($item, container, _super) {
      oldIndex = $item.index();
      $item.appendTo($item.parent());
      _super($item, container);
    },
    onDrop: function  ($item, container, _super) {
      var field,
          newIndex = $item.index();

      if(newIndex != oldIndex) {
        $item.closest('table').find('tbody tr').each(function (i, row) {
          row = $(row);
          if(newIndex < oldIndex) {
            //row.children().eq(newIndex).before(row.children()[oldIndex]);
          } else if (newIndex > oldIndex) {
            //row.children().eq(newIndex).after(row.children()[oldIndex]);
          }
        });
      }

      _super($item, container);
      $.post( "/room", { oldindex: oldIndex, newindex: newIndex, action: "drag" } ).done(function( data ) {
        socket.emit('chatMessage', "swap");
        //location.reload();
      });
    },
  });
</script>

<script>

  // Sortable rows
  var oldIndex;
  $('.sorted_table_vip').sortable({
    containerSelector: 'table',
    itemPath: '> tbody',
    itemSelector: 'tr',
    placeholder: '<tr class="placeholder"/>',
    onDragStart: function ($item, container, _super) {
      oldIndex = $item.index();
      $item.appendTo($item.parent());
      _super($item, container);
    },
    onDrop: function  ($item, container, _super) {
      var field,
          newIndex = $item.index();

      if(newIndex != oldIndex) {
        $item.closest('table').find('tbody tr').each(function (i, row) {
          row = $(row);
          if(newIndex < oldIndex) {
            //row.children().eq(newIndex).before(row.children()[oldIndex]);
          } else if (newIndex > oldIndex) {
            //row.children().eq(newIndex).after(row.children()[oldIndex]);
          }
        });
      }

      _super($item, container);
      $.post( "/room", { oldindex: oldIndex, newindex: newIndex, action: "dragVip" } ).done(function( data ) {
        socket.emit('chatMessage', "swap");
        //location.reload();
      });
    },
  });
</script>

<script type="text/javascript">       
$(document).ready(function(){
    $("#check_all").click(function(){
      var status=this.checked;
      $("input.selected_bnhan").each(function(){
        this.checked=status;
      });
    });
    $("#swapBnhan").click(function(){
      do_submit("swap");
    });
  });
  
  function do_submit(action)
  {
    if (!checkSelectedBnhan())
    {
      alert("Bạn cần chọn ít nhất 1 bản tin để thực hiện tiếp");
      return;
    }
    if (!confirm("Đây là thao tác không thể khôi phục lại. Bạn có chắc chắn thực hiện"))
      return;

    var arrayBnhanId = [];
    $("input.selected_bnhan").each(function(){
      if (this.checked)
      {
        arrayBnhanId.push($(this).val()); 
      }
    });
    var selectedRoom = $('#swapRoom :selected').val();
    $.post( "/room", { arrayBnhanId: arrayBnhanId, room:selectedRoom, action: "swap" } ).done(function( data ) {
        socket.emit('chatMessage', "swap");
        //location.reload();
    });
  }
  
  function checkSelectedBnhan()
  {
    var ok=false;
    $("input.selected_bnhan").each(function(){
      if (this.checked)
      {
        ok=true;
        return false;
      }
    });
    return ok;
  }

 </script>