<?php require_once APP_PATH.("config/room.php");?>

<div class="page-header">
    <h3></h3>
</div>
<div class="col-md-8">
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-sm-8">
                <?php if($msg != ''): ?>
                    <div class="alert alert-success">
                      <strong><?=$msg?></strong>
                    </div>
                <?php endif; ?>
            </div>
        </div>
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-4 control-label">Mã TC</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" name="tc" placeholder="Nhập mã TC" vaCue="<?=$tc?>" id="tc">
            </div>
        </div>
        <div class="form-group">
            <label for="room" class="col-sm-4 control-label">Chọn phòng khám:</label>
            <div class="col-sm-8">            
                <select class="form-control" name="room" id="room">
                    <?php foreach($room as $key=>$value): ?>
                        <option value="<?=$key?>" <?php if($key == $r): ?>selected<?php endif; ?>><?=$value?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="room" class="col-sm-4 control-label">Loại khách:</label>
            <div class="col-sm-8">            
                <select class="form-control" name="type" id="type">
                    <option value="0">Khách thường</option>
                    <option value="1">Khách đặt hẹn</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-8 pull-right">
                <button type="button" class="btn btn-danger" onclick="pushB();">Đồng ý</button>
            </div>
        </div>
    </div>
</div>
<script>
  var socket = io.connect('<?=NODE_SERVER?>');
  function pushB(){
    var tc = $("#tc").val();
    var room = $("#room option:selected").val();
    var type = $("#type option:selected").val();
    $.post( "/le-tan", { tc: tc, room: room,type: type } ).done(function( data ) {
        socket.emit('chatMessage', "pushBNhan");
        location.reload();
    });
  }
</script>