<style type="text/css">
body.dragging, body.dragging * {
  cursor: move !important;
}

.dragged {
  position: absolute;
  opacity: 0.5;
  z-index: 2000;
}

ol.example li.placeholder {
  position: relative;
  /** More li styles **/
}
ol.example li.placeholder:before {
  position: absolute;
  /** Define arrowhead **/
}
</style>
<div class="page-header">
    <?php $r = require_once APP_PATH.('config/room.php'); ?>
    <h3>Danh sách chờ <?=$r[$roomID]?></h3>
</div>
<div class="form-group" style="margin-bottom: 80px;">
            <label for="room" class="col-sm-4 control-label">Chọn phòng khám:</label>
            <div class="col-sm-8">            
                <select class="form-control" name="room" style="width: 150px;" id="room">
                    <?php foreach($r as $key=>$value): ?>
                        <option value="<?=$key?>" <?php if($key == $roomID): ?>selected<?php endif; ?>><?=$value?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
<div>
  </div>

<table class="table table-striped table-bordered sorted_table">
    <thead>
      <tr style="font-size: 20px;height: 75px;">
        <th style="font-size: 20px;">STT</th>
        <th style="font-size: 20px;">Tên Bệnh nhân</th>
        <th style="font-size: 20px;">Ngày sinh</th>
        <th style="font-size: 20px;">Giới tính</th>
        <th style="font-size: 20px;">Hành động</th>
      </tr>
    </thead>
    <tbody id="drapTable">
      <?php 
      $count = 0;
      foreach($bNhan as $b):
        $count++;
      ?>
      <tr style="height: 75px;">
        <td style="font-size: 20px;"><?=$b->sort?></td>
        <td style="font-size: 20px;"><?=$b->TEN_BNHAN?></td>
        <td style="font-size: 20px;"><?=$b->NGAY_SINH?></td>
        <td style="font-size: 20px;"><?php if($b->GIOI_TINH == 'M'){echo "Nam";}else{echo "Nữ";}?></td>
        <td style="font-size: 20px;">
          <?php if($b->status == 0): ?>
            <strong>Đang đợi</strong>
          <?php endif; ?>
          <?php if($b->status == 1): ?>
            <strong>Đang khám</strong>
          <?php endif; ?>
        </td>
      </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
<script>
  var socket = io.connect('<?=NODE_SERVER?>');

  $( "#room" ).change(function() {
    var roomID = $( "#room option:selected").val();
    location.href="/phong-kham?room="+roomID;
    //window.location("/phong-kham?room="+roomID);
  });

  socket.on('chatMessage', function(msg){
    if(msg == "swap" || msg == "callBNhan" || msg == "pushBNhan"){
      location.reload();
    }
  });

  // Sortable rows
  var oldIndex;
  $('.sorted_table').sortable({
    containerSelector: 'table',
    itemPath: '> tbody',
    itemSelector: 'tr',
    placeholder: '<tr class="placeholder"/>',
    onDragStart: function ($item, container, _super) {
      oldIndex = $item.index();
      $item.appendTo($item.parent());
      _super($item, container);
    },
    onDrop: function  ($item, container, _super) {
      var field,
          newIndex = $item.index();

      if(newIndex != oldIndex) {
        $item.closest('table').find('tbody tr').each(function (i, row) {
          row = $(row);
          if(newIndex < oldIndex) {
            //row.children().eq(newIndex).before(row.children()[oldIndex]);
          } else if (newIndex > oldIndex) {
            //row.children().eq(newIndex).after(row.children()[oldIndex]);
          }
        });
      }

      _super($item, container);
      $.post( "/receptionist/view", { oldindex: oldIndex, newindex: newIndex, action: "drag" } ).done(function( data ) {
        socket.emit('chatMessage', "swap");
        //location.reload();
      });
    },
  });
</script>